### ISSUE TITLE
Build with netCDF support

### ISSUE THREAD

**Issue by jpdark** [TileDB-Inc/TileDB-Geospatial#11]
I reckon it would be useful to build the gdal library in this image with netCDF support, so these can be translated to TileDB more easily.
I.e. I wanted to do something like
```shell
docker run --rm tiledb/tiledb-geospatial /bin/bash -c "gdalmdimtranslate -OF TileDB *.nc <array-name>"
```
yet this fails without netCDF support (in gdal, to be precise).

Would you consider doing this? 
I'm currently building a new image based on this one, rebuilding gdal with netCDF support. Would be happy to create a PR for this if there is interest.

**Comment by normanb** [comment]
@jpdark yes, we can enable netCDF support in this image.

You may have noticed our support for mapping netCDF files using GDAL subdatasets which was the traditional approach of reading netCDF within GDAL.

We are close to fully implementing https://gdal.org/user/multidim_raster_data_model.html with may give you a better GDAL experience with netCDF.

Can you share more about how you plan to use TileDB once you have this conversion in place? Please feel to send us a message on https://tiledb.com/

**Comment by jpdark** [comment]
@normanb Thanks for the swift response.

I'm only just starting out with TileDB. We're looking to use it for storing a large set of weather data `(x, y, t)` which we would parse spatially to get historical time-series or aggregations.

Great to hear you're implementing the multidimensional raster model. Do you have a public roadmap?

**Comment by normanb** [comment]
@jpdark we are using https://feedback.tiledb.com/ to prioritize public features, we have just created tiledb-geospatial tab for geo. If you have any features you would like added then please add to the board.

Your use case is interesting, let us know if we can help.  I will take a look at your PR, thank you

**Comment by jpdark** [comment]
Thanks! I'll get in touch once I get more familiar with the stack and dataset.
