### ISSUE TITLE
ByteBuffer does not exist for attribute: TDB_VALUES

### ISSUE THREAD

**Issue by OrlovDiga** [TileDB-Inc/TileDB-Geospatial#16]
Hi guys, I ran into the problem of reading data from an array.
Here are my steps:
1) Downloaded MBTiles data from this source (https://docs.tiledb.com/geospatial/gdal/)
2) Converted this to the correct format for TileDB using gdal (https://docs.tiledb.com/geospatial/gdal)
3) Created ArraySchema (https://javadoc.io/doc/io.tiledb/tiledb-java/latest/io/tiledb/java/api/ArraySchema.html) and checked the content with dump(screen 1)
<img width="227" alt="Снимок экрана 2020-11-10 в 11 14 09" src="https://user-images.githubusercontent.com/43121141/98647637-2f1c5180-2346-11eb-897f-43aa8c17b31b.png">
4)wrote the following code (https://gist.github.com/OrlovDiga/d117fa011aa20b9a97f24820e5a91083) and I get the exception described in the gist.

Question: How to solve this problem? And why the data is stored in the UINT8 format?

**Comment by OrlovDiga** [comment]
Ok I found a solution.
1) If our attribute has no offset, then the data is taken from the buffers_ field of the Query object. The getBuffer() method of the Query object can be used to get data. Next cast to need type.
2) If the attribute has offset, then the data is taken from the byteBuffers_ field of the Query object. To get the attribute in this case, you can use various methods that return Pair <SomethingBuffer, SomethingBuffer> of the Query object.

about the question about the storage type (UINT8)
Am I correct in thinking that the cell data represent RGBA color numbers?

**Comment by normanb** [comment]
@OrlovDiga the cell data type is determined by GDAL, in this case it is representing RGBA.

You might find it easier to use the Java bindings for GDAL and read a TileDB array that way as that hides some of the implementation. If you don't use GDAL then you will need to read the `_gdal` metadata from the TileDB array and parse the `.aux.xml` file which is written as part of `gdal_translate` to get the image data type and width/height.

**Comment by OrlovDiga** [comment]
OK, thank you for the information, @normanb. Then I close this issue.
