### ISSUE TITLE
Creating a TileDB array for RGBA data with `gdal_translate` often results in broken data

### ISSUE THREAD

**Issue by homme** [TileDB-Inc/TileDB-Geospatial#7]
@normanb if you remember this is the artefact issue we discussed briefly on our FATMAP call the other week; we're still running into it with newer versions of GDAL and TileDB. Running the following on a Linux x86_64 host should reproduce the issue:
```
echo "
set -e
cd /data
wget  --no-verbose https://eoimages.gsfc.nasa.gov/images/imagerecords/57000/57752/land_shallow_topo_east.tif
gdal_translate -of TileDB land_shallow_topo_east.tif ./test-array
gdal_translate -of GTiff ./test-array ./test-array.tif
" | docker run -i --rm -v $(pwd):/data tiledb/tiledb-geospatial@sha256:46913ae5cebd1bb5f93ed0399bff4446e59e211ccf59be7021b1efba919419ac bash
```
(This image is built from https://github.com/TileDB-Inc/TileDB-Geospatial/commit/893bc4bca37699bf7aca738c25e47480c71d6268)

I would expect the contents of `./test-array.tif` to be visually identical to `./land_shallow_topo_east.tif` but this is not the case, instead producing output with artefacts towards the bottom of the image:
![image](https://user-images.githubusercontent.com/1055336/72760211-f1d8ae80-3bcf-11ea-9a5d-8b92110e05d9.png)

Interestingly when running on a MacOS host this does not seem to be an issue. Also, smaller rasters often seem to be fine on Linux. Please let me know if there's anything else I can do to help with this, thanks!

**Comment by normanb** [comment]
@homme Thanks for reporting this issue and providing a test case. I can confirm I can recreate this bug with Ubuntu. I will look into this and report back.

**Comment by homme** [comment]
Fantastic, thanks @normanb!

**Comment by homme** [comment]
@normanb just to let you know we're still getting this issue using GDAL built with https://github.com/OSGeo/gdal/pull/2185 (commit c1f8e0d267d277d1d5359553c23a67d77311099f). Using this version of GDAL to update sub extents of an array causes the array to become unreadable using `gdalinfo` (which just hangs with no output, even when passing ` --debug on`).

**Comment by normanb** [comment]
@homme I am able to translate the array with this version of GDAL. I will create an update test we can share to see if I can recreate the issue you are seeing.

```
gdal_translate -of TileDB land_shallow_topo_east.tif ./test-array
Input file size is 21600, 21600
0...10...20...30...40...50...60...70...80...90...100 - done.

gdalinfo test-array 
Driver: TileDB/TileDB
Files: test-array/test-array.tdb
       test-array
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue

gdalinfo --version
GDAL 3.1.0dev-416fdf93e4-dirty, released 2020/01/28
```

**Comment by normanb** [comment]
```
import gdal
import numpy as np

tiledb_path = 'test-array'

update_ds = gdal.OpenEx(tiledb_path, gdal.GA_Update, allowed_drivers=["TileDB"])

new_data = np.zeros((10000, 1000)) * 255

for i in range(3):
  bnd = update_ds.GetRasterBand(i + 1)
  bnd.WriteArray(new_data)
  bnd = None

update_ds = None
```

Works for me with this image and makes a blank rectangle in the top left corner and I am able to view the metadata with `gdalinfo`. I am not sure which version of the tiledb-geospatial docker image you are using but the latest is using 1.7.2.

I will now look at the problem with the artefacts at the bottom of the image.

**Comment by svenjr** [comment]
I have also verified this using the GDAL version you mentioned @normanb (`GDAL 3.1.0dev-416fdf93e4, released 2020/01/28`). The first thing I verified is that the artifact issue is still occurring on Linux using 
`gdal_translate -of TileDB test.vrt tdb_test`
The output of this (viewed as a PNG) does still contain artifacts at the bottom like @homme 's original image. However, a `gdalinfo tdb_test` gives fine information. The issue we were seeing was when an update is pushed to the TDB array and then you gdalinfo it, the info hangs and doesn't return anything.

**Comment by normanb** [comment]
@amccalljr can you confirm with the Python snippet above? I can see the artifacts, but I can update the image and `gdalinfo` will return with the correct metadata.

I am working on the issue with the artifacts, I hope to be able to report back on this shortly.

**Comment by svenjr** [comment]
Hi @normanb , I have been doing some tests to see what I can reproduce. What I have done here is take @homme 's original photo (or the west part of it) and put two duplicate TDB arrays on s3. This first block shows that both arrays return information from a `gdalinfo` and that they are identical. 
(p.s. - I have used `[s3 path]` in place of the path for discretion)

Control Array Name: `world_array`
Update Array Name: `world_array_update`
```
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3 path]/world_array
Driver: TileDB/TileDB
Files: [s3 path]/world_array.tdb
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3 path]/world_array_update
Driver: TileDB/TileDB
Files: [s3 path]/world_array_update.tdb
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue 
```

When I run your update script on a **local** version of the array I made, the update works fine and the `gdalinfo` also works fine. The issue can be recreated when the same script is run (with some AWS options added) on the `world_update_array` in `s3`. When this is done (and this is the first update), this is when a `gdalinfo` does not work on the array. For some reason, when it is sitting in `s3` and an update is pushed (which also takes significantly longer) a `gdalinfo` fails.  The following block shows the same exact commands run **after** the update script ran on the `world_array_update` TDB array in `s3`:
```
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3 path]/world_array
Driver: TileDB/TileDB
Files: [s3 path]/world_array.tdb
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3 path]/world_array_udpate
ERROR 1: [TileDB::StorageManager] Error: Cannot open array; Array does not exist
gdalinfo failed - unable to open '[s3 path]/world_array_udpate'.
```

I hope this helps with some fact finding. I also hope the artefact issue is going well. Talk to you this week!

**Comment by svenjr** [comment]
**Updates on s3-update bug **

Since the last time I did these exact same tests, both TileDB and GDAL have had updates. We applied these new versions to our dev environment and, in-short, it seems like this metadata issue has disappeared. I will walk through the same tests as last time and share outputs below. 

Once again, I first created two TileDB arrays locally and two TileDB arrays in s3. One that is a control (`world_array`) and one which an update is applied to(`world_array_update`) with the snippet of code above provided by @normanb. The local stuff still all works so the output code I will be posting is only in reference to the `s3` arrays. First I create both arrays in `s3` and test that their `gdalinfo` metadata returns identical and at all. The first line also shows us that we are in the right dev environment and using the most up-to-date gdal. Once again, I have removed the base `s3` path with `[s3_path]` for discretion:

```bash-5.0# gdalinfo --version 
GDAL 3.1.0dev-f5b796bf64, released 2020/02/05
bash-5.0# gdal_translate -co TILEDB_CONFIG=aws.config -of TILEDB tmp/live-avy/land_shallow_west.tif [s3_path]/world_array
Input file size is 21600, 21600
0...10...20...30...40...50...60...70...80...90...100 - done.
bash-5.0# gdal_translate -co TILEDB_CONFIG=aws.config -of TILEDB tmp/live-avy/land_shallow_west.tif [s3_path]/world_array_update
Input file size is 21600, 21600
0...10...20...30...40...50...60...70...80...90...100 - done.
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3_path]/world_array
Driver: TileDB/TileDB
Files:[s3_path]/world_array.tdb
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3_path]/world_array_update
Driver: TileDB/TileDB
Files: [s3_path]/world_array_update.tdb
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue 
```

The next piece I do  is update `world_array_update` with Norman's python snippet from above in `s3` (with a small open-options addition). Once the update is complete, I test each array's metadata return with `gdalinfo`. Now in the comment above (and on the older versions) this was failing on the updated array, but as you can see here, it now works:

``` 
bash-5.0# python3 tmp/live-avy/test_update.py 
BAND: 1
BAND: 2
BAND: 3
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3_path]/world_array
Driver: TileDB/TileDB
Files: [s3_path]/world_array.tdb
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
bash-5.0# gdalinfo -oo TILEDB_CONFIG=aws.config [s3_path]/world_array_update
Driver: TileDB/TileDB
Files: [s3_path]/world_array_update.tdb
Size is 21600, 21600
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  DATA_TYPE=Byte
  NBITS=8
  X_SIZE=21600
  Y_SIZE=21600
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,21600.0)
Upper Right (21600.0,    0.0)
Lower Right (21600.0,21600.0)
Center      (10800.0,10800.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
```

The last thing I verified is that the actual array in `s3` did update. This we can see in the photo below where the top left corner is blanked out (like the script tells it to do):
![s3_update_PNG](https://user-images.githubusercontent.com/36718299/74053412-0c869200-49dc-11ea-9ae5-e161172afd32.png)

So, it is unclear what happened in these updates but this bug seems to have gone away in one of these updates (TileDB 1.7.5 or GDAL 3.1.0dev-f5b796bf64). So I guess we are back to just the artefacts which is a good thing!

**Comment by normanb** [comment]
@amccalljr great that the updates work. For the artifacts we are working up a separate test case (outside of GDAL) to see where this bug lies. As you noted it does seem OS specific. I will report back when we know more.

**Comment by homme** [comment]
@normanb I've just tried the latest `tiledb-geospatial` image against this issue and am getting this output:

![image](https://user-images.githubusercontent.com/1055336/77761344-cf2f9f80-702f-11ea-8d8c-acd0b9ee3435.png)

This is generated by the following script run on x86_64 GNU/Linux:

```echo "
set -e
cd /data
wget  --no-verbose https://eoimages.gsfc.nasa.gov/images/imagerecords/57000/57752/land_shallow_topo_east.tif
gdal_translate -of TileDB land_shallow_topo_east.tif ./test-array
gdal_translate -of GTiff ./test-array ./test-array.tif
" | docker run -i --rm -v $(pwd):/data tiledb/tiledb-geospatial@sha256:34192a268aadfe3ca98af32276a0bc49aa34a83431f72de6cc5aab072c3ee705 bash
```
I also believe @amccalljr is now experiencing similar artefacting where he didn't before when running on his mac. 

Much as we'd love to continue experimenting with TileDB in our workflows this issue is a blocker for us: we're just wondering if it's something that is actively being worked on or is it lower down your priority list?

Many thanks!

**Comment by normanb** [comment]
@homme I can recreate the artifacts with 256x256 tiles in GDAL but not with 512x512 tiles. I am actively working on this issue now. To change the blocksize use `-CO BLOCKXSIZE=512 -CO BLOCKYSIZE=512` with `gdal_translate` when creating the array from the global image. 

I will update this ticket at the end of tomorrow (Friday) with my findings.

**Comment by normanb** [comment]
@homme An update: I have created a standalone C++ TileDB writer (with no dependencies) for tiled TIFF Files and created a TileDB array from the sample image that is failing. The artifacts do not exist in this case. This points to there being an issue in the GDAL driver itself which I will debug.

**Comment by normanb** [comment]
@homme I have solved the artifact issue here - this is the GDAL_CACHEMAX variable, when using `gdal_translate` please `export GDAL_CACHEMAX=0`, GDAL cache isn't needed for this operation.

I will work on an internal fix to the GDAL TileDB driver (or higher up in the GDAL code) to support the GDAL cache in case this environment variable isn't set and it explains why we were only seeing this with smaller tiles and larger files. The cache isn't serving tiles in order to `WriteBlock`

Thank you for your patience as we worked through this.
